[deploy]
bucket = 'cruddur-cfn-artifacts-3241'
region = 'us-east-2'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://drummer-test-app.online'
EnvBackendUrl = 'https://api.drummer-test-app.online'