[deploy]
bucket = 'cruddur-cfn-artifacts-3241'
region = 'us-east-2
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipline-cruddur-cfn-artifacts-3241"